local this = {}

this.vanillaTable = {
	-- Morrowind
	["addhiranirr"] = { entry = "A2_4_MiloGone", index = 1 },
	["athyn sarethi"] = { entry = "B5_RedoranHort", index = 50 },
	["Blatta Hateria"] = { entry = "A2_4_MiloGone", index = 50 },
	["caius cosades"] = { entry = "A2_4_MiloGone", index = 1 },
	["crassius curio"] = { entry = "B6_HlaaluHort", index = 50 },
	["danso indules"] = { entry = "B8_MeetVivec", index = 50 },
	["divayth fyr"] = { entry = "A2_4_MiloGone", index = 1 },
	["dram bero"] = { entry = "B6_HlaaluHort", index = 50 },
	["dutadalk"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["endryn llethan"] = { entry = "B8_MeetVivec", index = 50 },
	["falura llervu"] = { entry = "B3_ZainabBride", index = 50 },
	["garisa llethri"] = { entry = "B5_RedoranHort", index = 50 },
	["gilvas barelo"] = { entry = "A2_4_MiloGone", index = 50 },
	["han-ammu"] = { entry = "B4_KillWarLovers", index = 55 },
	["hasphat antabolis"] = { entry = "A2_4_MiloGone", index = 1 },
	["hassour zainsubani"] = { entry = "A2_4_MiloGone", index = 1 },
	["hlaren ramoran"] = { entry = "B5_RedoranHort", index = 50 },
	["huleeya"] = { entry = "A2_4_MiloGone", index = 1 },
	["kaushad"] = { entry = "B3_ZainabBride", index = 50 },
	["kausi"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["manirai"] = { entry = "B4_KillWarLovers", index = 55 },
	["mehra milo"] = { entry = "A2_4_MiloGone", index = 50 },
	["miner arobar"] = { entry = "B5_RedoranHort", index = 50 },
	["brara morvayn"] = { entry = "B5_RedoranHort", index = 50 },
	["nevena ules"] = { entry = "B6_HlaaluHort", index = 50 },
	["nibani maesa"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["raesa pullia"] = { entry = "A2_4_MiloGone", index = 1 },
	["savile imayn"] = { entry = "B3_ZainabBride", index = 50 },
	["sharn gra-muzgob"] = { entry = "A2_4_MiloGone", index = 1 },
	["sinnammu mirpal"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["sonummu zabamat"] = { entry = "B3_ZainabBride", index = 50 },
	["sul-matuul"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["tholer saryoni"] = { entry = "B8_MeetVivec", index = 50 },
	["uupse fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["varvur sarethi"] = { entry = "B5_RedoranHort", index = 50 },
	["velanda omani"] = { entry = "B6_HlaaluHort", index = 50 },
	["vivec_god"] = { entry = "B8_MeetVivec", index = 50 },
	["yagrum bagarn"] = { entry = "C3_DestroyDagoth", index = 50 },
	["yenammu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["zabamund"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	-- Tribunal
	["almalexia"] = { entry = "TR_SothaSil", index = 100 },
	["apelles matius"] = { entry = "TR_DBAttack", index = 50 },
	["barenziah"] = { entry = "TR_SothaSil", index = 100 },
	["fedris hler"] = { entry = "TR_SothaSil", index = 100 },
	["gavas drin"] = { entry = "TR_MazedBand", index = 90 },
	["karrod"] = { entry = "TR_Blade", index = 35 },
	["King Hlaalu Helseth"] = { entry = "TR_SothaSil", index = 100 },
	["dwarven ghost_radac"] = { entry = "TR_Blade", index = 80 },
	["Tienius Delitian"] = { entry = "TR_SothaSil", index = 100 },
	-- Bloodmoon
	["falx carius"] = { entry = "BM_WildHunt", index = 100 },
	["tharsten heart-fang"] = { entry = "BM_WildHunt", index = 64 },
}
this.extendedTable = {
	-- Morrowind
	["ababael timsar-dadisun"] = { entry = "B3_ZainabBride", index = 50 },
	["addammus"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["addut-lamanu"] = { entry = "B4_KillWarLovers", index = 55 },
	["ahasour"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["alfe fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["ashibaal"] = { entry = "B3_ZainabBride", index = 50 },
	["ashur-dan"] = { entry = "B3_ZainabBride", index = 50 },
	["assamma-idan"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["assemmus"] = { entry = "B4_KillWarLovers", index = 55 },
	["beyte fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["bolvyn venim"] = { entry = "B5_RedoranHort", index = 50 },
	["delte fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["hainab"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["kammu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["kummu"] = { entry = "B4_KillWarLovers", index = 55 },
	["kurapli"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["lanabi"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["mabarrabael"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["maeli"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["mamaea"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["massarapal"] = { entry = "B4_KillWarLovers", index = 55 },
	["mausur"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["minassour"] = { entry = "B3_ZainabBride", index = 50 },
	["ninirrasour"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["nummu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["patababi"] = { entry = "B3_ZainabBride", index = 50 },
	["sakiran"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["sakulerib"] = { entry = "B3_ZainabBride", index = 50 },
	["chargen captain"] = { entry = "A1_1_FindSpymaster", index = 1 },
	["sen"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["senipu"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shabinbael"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shallath-piremus"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shara"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shimsun"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["tussi"] = { entry = "B3_ZainabBride", index = 50 },
	["tussurradad"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["ulabael"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["ulibabi"] = { entry = "B4_KillWarLovers", index = 55 },
	["urshamusa rapli"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["vistha_kai"] = { entry = "A2_3_CorprusCure", index = 50 },
	["yantus"] = { entry = "B4_KillWarLovers", index = 55 },
	["yen"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["zaba"] = { entry = "B3_ZainabBride", index = 50 },
	["zallit"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["zanummu"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["zebba"] = { entry = "B4_KillWarLovers", index = 55 },
}
this.questItemTable = {
	-- Morrowind
	["bk_a1_1_caiuspackage"] = { entry = "A1_1_FindSpymaster", index = 12 },
	["lugrub's axe"] = { entry = "IL_WidowLand", index = 70 },
	["dwarven war axe_redas"] = { entry = "HR_RedasTomb", index = 100 },
	["ebony staff caper"] = { entry = "TG_EbonyStaff", index = 100 },
	["Rusty_Dagger_UNIQUE"] = { entry = "DA_Mehrunes", index = 40 },
	["devil_tanto_tgamg"] = { entry = "TG_LootAldruhnMG", index = 100 },
	["daedric wakizashi_hhst"] = { entry = "HH_SunkenTreasure", index = 100 },
	["glass_dagger_enamor"] = { entry = "TG_SS_Enamor", index = 100 },
	["fork_horripilation_unique"] = { entry = "DA_Sheogorath", index = 70 },
	["dart_uniq_judgement"] = { entry = "TG_DartsJudgement", index = 100 },
	["bonemold_gah-julan_hhda"] = { entry = "HH_DisguisedArmor", index = 50 },
	["bonemold_founders_helm"] = { entry = "HR_FoundersHelm", index = 100 },
	["bonemold_tshield_hrlb"] = { entry = "HR_LostBanner", index = 100 },
	["amuletfleshmadewhole_uniq"] = { entry = "HT_FleshAmulet", index = 100 },
	["amulet_Agustas_unique"] = { entry = "MS_ArenimTomb", index = 110 },
	["expensive_amulet_delyna"] = { entry = "HR_MadMilk", index = 90 },
	["expensive_amulet_aeta"] = { entry = "MV_BanditVictim", index = 100 },
	["sarandas_amulet"] = { entry = "Town_Ald_Bevene", index = 3 },
	["exquisite_amulet_hlervu1"] = { entry = "TG_SS_Generosity1", index = 30 },
	["Julielle_Aumines_Amulet"] = { entry = "IC19_Restless_Spirit", index = 40 },
	["Linus_Iulus_Maran Amulet"] = { entry = "IC18_Silver_Staff", index = 50 },
	["Linus_Iulus_Stendarran_Belt"] = { entry = "IC18_Silver_Staff", index = 50 },
	["sarandas_belt"] = { entry = "Town_Ald_Tiras", index = 3 },
	["extravagant_rt_art_wild"] = { entry = "TT_AldDaedroth", index = 100 },
	["expensive_glove_left_ilmeni"] = { entry = "IL_MaidenToken", index = 70 },
	["extravagant_glove_left_maur"] = { entry = "MV_VictimRomance", index = 50 },
	["common_pants_02_hentus"] = { entry = "MS_HentusPants", index = 100 },
	["sarandas_pants_2"] = { entry = "Town_Ald_Bivale", index = 3 },
	["Adusamsi's_Ring"] = { entry = "IC27_Oracle", index = 50 },
	["extravagant_ring_aund_uni"] = { entry = "VA_VampChild", index = 80 },
	["ring_blackjinx_uniq"] = { entry = "HT_BlackJinx", index = 100 },
	["exquisite_ring_brallion"] = { entry = "TG_SS_GreedySlaver", index = 50 },
	["common_ring_danar"] = { entry = "EB_DeadMen", index = 60 },
	["sarandas_ring_2"] = { entry = "Town_Ald_Daynes", index = 3 },
	["ring_keley"] = { entry = "MS_FargothRing", index = 100 },
	["expensive_ring_01_BILL"] = { entry = "MV_LostRing", index = 30 },
	["expensive_ring_aeta"] = { entry = "MV_BanditVictim", index = 100 },
	["sarandas_ring_1"] = { entry = "Town_Ald_Daynes", index = 3 },
	["Expensive_Ring_01_HRDT"] = { entry = "HR_DagothTanis", index = 100 },
	["exquisite_ring_processus"] = { entry = "MV_DeadTaxman", index = 90 },
	["Extravagant_Robe_01_Red"] = { entry = "HR_RedasTomb", index = 100 },
	["robe of st roris"] = { entry = "HH_WinSaryoni", index = 70 },
	["exquisite_robe_drake's pride"] = { entry = "HT_DrakePride", index = 100 },
	["sarandas_shirt_2"] = { entry = "Town_Ald_Bivale", index = 3 },
	["exquisite_shirt_01_rasha"] = { entry = "MV_TraderLate", index = 40 },
	["sarandas_shoes_2"] = { entry = "Town_Ald_Llethri", index = 3 },
	["therana's skirt"] = { entry = "HT_TheranaClothes", index = 100 },
	["misc_Beluelle_silver_bowl"] = { entry = "MS_Piernette", index = 90 },
	["misc_lw_bowl_chapel"] = { entry = "IC15_Missing_Limeware", index = 50 },
	["misc_dwrv_artifact_ils"] = { entry = "IL_Smuggler", index = 100 },
	["misc_dwarfbone_unique"] = { entry = "EB_Bone", index = 30 },
	["misc_dwrv_ark_cube00"] = { entry = "A1_2_AntabolisInformant", index = 10 },
	["Misc_fakesoulgem"] = { entry = "MG_Sabotage", index = 100 },
	["ingred_guar_hide_girith"] = { entry = "MV_OutcastAshlanders", index = 100 },
	["misc_uniq_egg_of_gold"] = { entry = "FG_FindPudai", index = 100 },
	["misc_goblet_dagoth"] = { entry = "A2_6_Incarnate", index = 15 },
	["ingred_guar_hide_marsus"] = { entry = "MV_InnocentAshlanders", index = 100 },
	["misc_6th_ash_hrmm"] = { entry = "HR_MorvaynManor", index = 50 },
	["misc_de_goblet_01_redas"] = { entry = "HR_RedasTomb", index = 100 },
	["misc_Skull_Llevule"] = { entry = "A1_4_MuzgobInformant", index = 15 },
	["misc_6th_ash_hrcs"] = { entry = "HR_ClearSarethi", index = 90 },
	["misc_wraithguard_no_equip"] = { entry = "CX_BackPath", index = 50 },
	["p_cure_common_unique"] = { entry = "MS_Apologies", index = 100 },
	["p_lovepotion_unique"] = { entry = "EB_Unrequited", index = 80 },
	["p_quarrablood_unique"] = { entry = "VA_VampBlood", index = 40 }, { entry = "VA_VampBlood2", index = 100 },
	["p_sinyaramen_unique"] = { entry = "VA_VampChild", index = 70 },
	["ingred_raw_glass_tinos"] = { entry = "MV_AngryTrader", index = 100 },
	["ingred_gold_kanet_unique"] = { entry = "MS_Gold_kanet_flower", index = 100 },
	["ingred_treated_bittergreen_uniq"] = { entry = "DA_Mephala", index = 57 },
	["bk_aedra_tarer_unique"] = { entry = "MS_Apologies", index = 10 },
	["glory_unique"] = { entry = "DA_Boethiah", index = 60 },
	["bk_sharnslegionsofthedead"] = { entry = "MG_Sharn_Necro", index = 10 },
	["bk_alen_note"] = { entry = "TR08_Hlaalu", index = 60 },
	["bk_irano_note"] = { entry = "TR07_Guard", index = 100 },
	["bk_Airship_Captains_Journal"] = { entry = "BM_Airship", index = 70 },
	["bk_snowprince"] = { entry = "BM_Falmer", index = 100 },
	["bk_sovngarde"] = { entry = "BM_BrodirGrove", index = 40 },
	["bk_ajira1"] = { entry = "MG_StolenReport", index = 100 },
	["bk_ajira2"] = { entry = "MG_StolenReport", index = 100 },
	["bk_landdeed_hhrd"] = { entry = "HH_ReplaceDocs", index = 100 },
	["bk_auranefrernis1"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_auranefrernis2"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_auranefrernis3"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_calderaminingcontract"] = { entry = "HH_CaptureSpy", index = 100 },
	["bk_clientlist"] = { entry = "EB_Clients", index = 40 },
	["bk_indreledeed"] = { entry = "TG_SS_Generosity2", index = 50 },
	["bk_dispelrecipe_tgca"] = { entry = "TG_CookbookAlchemy", index = 50 },
	["bk_drenblackmail"] = { entry = "B6_HlaaluHort", index = 50 },
	["bk_uleni's_papers"] = { entry = "town_Sadrith", index = 50 },
	["bk_itermerelsnotes"] = { entry = "MG_EscortScholar2", index = 100 },
	["bk_kagrenac'sjournal_excl"] = { entry = "CX_BackPath", index = 25 },
	["bk_kagrenac'splans_excl"] = { entry = "CX_BackPath", index = 25 },
	["bk_letterfromjzhirr"] = { entry = "EB_Express", index = 30 },
	["bk_letterfromllaalam"] = { entry = "EB_Express", index = 50 },
	["bk_letterfromllaalam2"] = { entry = "EB_TradeSpy", index = 40 },
	["bk_ocato_recommendation"] = { entry = "MG_Guildmaster", index = 50 },
	["bk_a1_2_introtocadiusus"] = { entry = "MG_Excavation", index = 20 },
	["bk_messagefrommasteraryon"] = { entry = "HT_FyrMessage", index = 50 },
	["bk_nemindasorders"] = { entry = "HH_DisguisedArmor", index = 100 },
	["bk_a1_4_sharnsnotes"] = { entry = "A1_4_MuzgobInformant", index = 25 },
	["bk_notefrombashuk"] = { entry = "MV_Bugrol", index = 40 },
	["bk_notefrombugrol"] = { entry = "MV_Bugrol", index = 30 },
	["bk_notefromernil"] = { entry = "MV_SkoomaCorpse", index = 20 },
	["bk_notefromnelos"] = { entry = "MV_VictimRomance", index = 100 },
	["bk_talostreason"] = { entry = "IL_TalosTreason", index = 50 },
	["bk_notetoamaya"] = { entry = "A2_4_MiloGone", index = 10 },
	["bk_enamor"] = { entry = "TG_SS_Enamor", index = 100 },
	["bk_a1_7_huleeyainformant"] = { entry = "A1_V_VivecInformants", index = 50 },
	["bk_landdeedfake_hhrd"] = { entry = "HH_ReplaceDocs", index = 50 },
	["bk_orderesforbivaleteneran"] = { entry = "HH_IndEsp3", index = 50 },
	["bk_progressoftruth"] = { entry = "A1_V_VivecInformants", index = 50 },
	["chargen statssheet"] = { entry = "A1_1_FindSpymaster", index = 1 },
	["bk_responsefromdivaythfyr"] = { entry = "HT_FyrMessage", index = 100 },
	["bk_stronghold_ld_hlaalu"] = { entry = "HH_Stronghold", index = 50 },
	["bk_calderarecordbook2"] = { entry = "HR_CalderaCorrupt", index = 100 },
	["bk_seniliasreport"] = { entry = "MG_Excavation", index = 100 },
	["bk_shishireport"] = { entry = "HR_ShishiReport", index = 100 },
	["bk_sottildescodebook"] = { entry = "FG_Sottilde", index = 100 },
	["bk_tiramgadarscredentials"] = { entry = "MG_SpyCatch", index = 100 },
	["bk_treasury orders"] = { entry = "HH_BankFraud", index = 50 },
	["bk_treasury report"] = { entry = "HH_BankCourier", index = 50 },
	["bk_contract_ralen"] = { entry = "EB_Deed", index = 40 },
	["bk_widowdeed"] = { entry = "IL_WidowLand", index = 100 },
	["bk_ynglingledger"] = { entry = "TG_SS_Yngling", index = 100 },
	["bk_a1_11_zainsubaninotes"] = { entry = "A2_1_MeetSulMatuul", index = 1 },
	-- Tribunal
	["ebony war axe_elanande"] = { entry = "MS_Warlords", index = 70 },
	["dwarven mace_salandas"] = { entry = "MS_Warlords", index = 120 },
	["silver dagger_droth_unique_a"] = { entry = "MS_EstateSale", index = 60 },
	["silver dagger_droth_unique"] = { entry = "MS_EstateSale", index = 60 },
	["ebony shortsword_soscean"] = { entry = "MS_Warlords", index = 40 },
	["silver spear_uvenim"] = { entry = "MS_Warlords", index = 100 },
	["ebony_cuirass_soscean"] = { entry = "MS_Warlords", index = 40 },
	["silver_helm_uvenim"] = { entry = "MS_Warlords", index = 100 },
	["amulet_salandas"] = { entry = "MS_Warlords", index = 120 },
	["extravagant_robe_02_elanande"] = { entry = "MS_Warlords", index = 70 },
	["bladepiece_02"] = { entry = "TR_Blade", index = 65 },
	["bladepiece_03"] = { entry = "TR_Blade", index = 65 },
	["dwemer_shield_battle_unique"] = { entry = "TR_Blade", index = 65 },
	["misc_dwrv_weather"] = { entry = "TR_ShowPower", index = 90 },
	["misc_dwrv_weather2"] = { entry = "TR_ShowPower", index = 90 },
	["bk_playscript"] = { entry = "MS_Performers", index = 30 },
	["sc_chridittepanacea"] = { entry = "MS_CrimsonPlague", index = 110 },
	["pyroil_tar_unique"] = { entry = "TR_Blade", index = 80 },
	-- Bloodmoon
	["fur_colovian_helm_white"] = { entry = "BM_MoonSugar", index = 100 },
	["amulet of infectious charm"] = { entry = "BM_Airship", index = 80 },
	["expensive_ring_erna"] = { entry = "BM_WomanScorned", index = 100 },
	["BM_bearheart_UNIQUE"] = { entry = "BM_BearHunt1", index = 100 },
	["misc_skull_oddfrid"] = { entry = "BM_SadSeer", index = 40 },
	["misc_skull_Skaal"] = { entry = "BM_CariusGone", index = 100 },
	["BM_Seeds_UNIQUE"] = { entry = "BM_Trees", index = 40 },
	["Misc_BM_ClawFang_UNIQUE"] = { entry = "BM_Ceremony1", index = 100 },
	["BM_waterlife_UNIQUE1"] = { entry = "BM_Water", index = 100 },
	["bk_BMtrial_unique"] = { entry = "BM_Trial", index = 55 },
	["bk_colony_Toralf"] = { entry = "CO_13", index = 40 },
	["ingred_emerald_pinetear"] = { entry = "BM_Retribution", index = 100 },
	["ingred_innocent_heart"] = { entry = "BM_WolfGiver", index = 100 },
	["ingred_wolf_heart"] = { entry = "BM_WolfGiver", index = 105 },
}
return this